### ISSUE TITLE
Favicon funktioniert nicht mehr

### ISSUE THREAD

**Issue by mikeboy91** [thextor/readmore-userscript#90]
Mir ist aufgefallen, dass das Ändern der Favicons nicht mehr funktioniert bzw. dass die Links in der entsprechenden Funktion tot sind.
http://readmore.thextor.de/userscript/img/favicon.png für ungelesene Posts im Thread und http://themes.cdn.readmore.de/readmore/favicon.ico das orginal Favicon.

Vielleicht könnte man ja auch [Favico.js](https://github.com/ejci/favico.js) dafür verwenden. Keine Ahnung ob und wie gut sich das dann hier einsetzen lässt.

**Comment by thextor** [comment]
Probleme in 4.6.0 behoben
